services:
  app:
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    networks:
      - ve_network

  scylla-node1:
    image: scylladb/scylla:6.1
    container_name: scylla-node1
    ports:
      - "9042:9042"  # CQL port
      - "7000:7000"  # Internal cluster port
    environment:
      - SCYLLA_CLUSTER_NAME=mycluster
      - SCYLLA_LISTEN_ADDRESS=0.0.0.0
      # - SCYLLA_SEEDS=scylla-node1,scylla-node2
    volumes:
      - ./Database/scylla:/var/lib/scylla
    networks:
      - ve_network
    depends_on:
      - redis
  redis:
    image: redis:7.4.0
    container_name: redis
    ports:
      - "6379:6379"  # Redis port
    networks:
      - ve_network
    

    
networks:
  ve_network:
    driver: bridge
volumes:
  scylla_data:
    driver: local
