services:
  app:
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    networks:
      - ve_network

  scylla:
    image: scylladb/scylla:6.1
    container_name: some-scylla
    ports:
      - "9042:9042"  # CQL port
      - "7000:7000"  # Internal cluster port
    environment:
      - SCYLLA_CLUSTER_NAME=mycluster
      - SCYLLA_LISTEN_ADDRESS=0.0.0.0
    networks:
      - ve_network

  redis:
    image: redis:7.4.0
    container_name: some-redis
    ports:
      - "6379:6379"  # Redis port
    networks:
      - ve_network

networks:
  ve_network:
    driver: bridge
