services:
  app:
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    networks:
      - scylla_network
  scylla:
    image: scylladb/scylla
    container_name: some-scylla
    ports:
      - "9042:9042"  # CQL port
      - "7000:7000"  # Internal cluster port
    environment:
      - SCYLLA_CLUSTER_NAME=mycluster
      - SCYLLA_LISTEN_ADDRESS=0.0.0.0
    networks:
      - scylla_network
networks:
  scylla_network:
    driver: bridge
